---
abstract: 'Yet another SQL builder'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
  Tie::IxHash: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Maker
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  SQL::Maker:
    file: lib/SQL/Maker.pm
    version: 1.10
  SQL::Maker::Condition:
    file: lib/SQL/Maker/Condition.pm
    version: 0
  SQL::Maker::Plugin::InsertMulti:
    file: lib/SQL/Maker/Plugin/InsertMulti.pm
    version: 0
  SQL::Maker::Plugin::InsertOnDuplicate:
    file: lib/SQL/Maker/Plugin/InsertOnDuplicate.pm
    version: 0
  SQL::Maker::SQLType:
    file: lib/SQL/Maker/SQLType.pm
    version: 0
  SQL::Maker::Select:
    file: lib/SQL/Maker/Select.pm
    version: 0
  SQL::Maker::Select::Oracle:
    file: lib/SQL/Maker/Select/Oracle.pm
    version: 0
  SQL::Maker::SelectSet:
    file: lib/SQL/Maker/SelectSet.pm
    version: 0
  SQL::Maker::Util:
    file: lib/SQL/Maker/Util.pm
    version: 0
requires:
  Class::Accessor::Lite: 0.05
  DBI: 0
  Module::Load: 0
  parent: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 1.10
